### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by 3052** [itzTheMeow/YTMusic#9]
any instruction?

**Comment by itzTheMeow** [comment]
there's not really any instructions for it right now

install go, node and pnpm
you can clone the repo
copy config.example.yaml as config.yaml and edit it (put in spotify api details after making an application)
run `go mod tidy` in the server directory to install the go dependencies
run start.sh and it'll build the client and copy your config to the `out` directory
then you can run the `YTMusic` binary in the out directory

**Comment by itzTheMeow** [comment]
I just filled out the README with a full set of instructions.
